## Matrix Multiplication in Numpy
<center><img src="images/matrix.png" width=700></center>

In [2]:
import numpy as np
A = np.array([[1, -1, 0.1],
             [2, -2, 0.2]])
AT = A.T

AT

array([[ 1. ,  2. ],
       [-1. , -2. ],
       [ 0.1,  0.2]])

In [3]:
W = np.array([[3, 5, 7, 9],
              [4, 6, 8, 0]])

In [4]:
Z = np.matmul(AT, W)
Z

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [  1.1,   1.7,   2.3,   0.9]])

In [6]:
# or
Z = AT @ W
Z

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [  1.1,   1.7,   2.3,   0.9]])

## Vectorized Implementation of forward prop

In [7]:
# usual input
AT = [[200, 17]]   # a 1 x 2 matrix
W = [[1, -3, 5],
    [-2, 4, -6]]
B = [[-1, 1, 2]]    # a 1 x 3 matrix

In [8]:
Z = np.matmul(AT, W) + B

In [9]:
Z

array([[ 165, -531,  900]])

In [ ]:
def g(Z):
    """ The activation function """
    pass

def dense(AT, W, B):
    Z = np.matmul(AT, W) + B
    A_out = g(Z)
    return A_out